services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api_keys.db:/root/api_keys.db
      - ./out:/root/out
    environment:
      - DATABASE_URL=file:./api_keys.db
      - REDIS_ADDR=redis:6379
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  db_data:
  redis_data: